# Generated by Django 3.2.3 on 2025-07-17 10:14

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250717_1308'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='users_subscribe_unique_following',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='users_subscribe_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='users_subscribe_unique_subscription'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('author')), _negated=True), name='users_subscribe_prevent_self_subscription'),
        ),
    ]
