version: '3'

volumes:
  pg_data:
  static:
  media:
services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: ../.env
  backend:
    build: ../backend/foodgram_backend/
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    build: ../frontend
    env_file: ../.env
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/
  nginx:
    build: .
    env_file: ../.env
    depends_on:
      - frontend
    ports:
      - "8000:80" #было 80:80
    volumes:
      - static:/staticfiles
      - media:/media/